
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
  application:
    name: compcany-frame
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Kehong0028..
      url: jdbc:mysql://42.194.140.230:3306/company_frame?serverTimezone=UTC&useUnicode=utf-8&useSSL=false
      ################## 连接池配置 ################
      #连接池建立时创建的初始化连接数
      initial-size: 5
      #连接池中最大的活跃连接数
      max-active: 20
      #连接池中最小的活跃连接数
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      query-timeout: 30000
      #是否在获得连接后检测其可用性
      test-on-borrow: false
      #是否在连接放回连接池后检测其可用性
      test-on-return: false
      #是否在连接空闲一段时间后检测其可用性
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall
      #设置监控页面的登录名和密码
#      stat-view-servlet:
#        login-username: admin
#        login-password: 666666
  redis:
    host: 42.194.140.230
    port: 6379
#    password: 123456
    lettuce:
      pool:
        max-active: 100
        max-idle: 20
        max-wait: PT10S
        min-idle: 1
    timeout: PT10S
logging:
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
  level:
    cn.codewoo: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
swagger:
  enable: true
# JWT相关配置
jwt:
  secretKey: 789448488448848fg)
  accessTokenExpireTime: PT2H
  refreshTokenExpireTime: PT8H
  refreshTokenExpireAppTime: P30D
  issuer: codewoo.cn